set_project("shoot-them")
set_languages("cxx17")

includes("samples/01-create-window/xmake.lua")
includes("samples/02-init-opengl/xmake.lua")
includes("samples/03-fps-camera/xmake.lua")
includes("samples/04-render-mesh/xmake.lua")
includes("samples/05-texture/xmake.lua")
includes("samples/06-lighting/xmake.lua")
includes("samples/07-model-loading/xmake.lua")
includes("samples/08-frame-buffer/xmake.lua")
