set_project("shoot-them")
set_languages("cxx17")

includes("samples/01-create-window/xmake.lua")
includes("samples/02-init-opengl/xmake.lua")
includes("samples/03-fps-camera/xmake.lua")
includes("samples/04-render-mesh/xmake.lua")
includes("samples/05-texture/xmake.lua")
includes("samples/06-lighting/xmake.lua")
includes("samples/07-model-loading/xmake.lua")
includes("samples/08-frame-buffer/xmake.lua")
includes("samples/09-shadow-mapping/xmake.lua")
includes("samples/10-particles/xmake.lua")
includes("samples/11-instance-rendering/xmake.lua")
includes("samples/12-cascade-shadow-mapping/xmake.lua")
includes("samples/13-terrain/xmake.lua")
includes("samples/14-point-light/xmake.lua")
includes("samples/15-bloom/xmake.lua")
includes("samples/16-anti-aliasing/xmake.lua")
includes("samples/17-skybox/xmake.lua")
includes("samples/18-reflection/xmake.lua")
-- includes("samples/19-gui/xmake.lua")
-- includes("samples/20-scripting/xmake.lua")
includes("samples/21-deferred-rendering/xmake.lua")
includes("samples/22-fast-approximation-anti-aliasing/xmake.lua")
includes("samples/23-multi-sample-anti-aliasing/xmake.lua")
includes("samples/24-screen-space-ambient-occlusion/xmake.lua")
includes("samples/25-horizon-based-ambient-occlusion/xmake.lua")
