#pragma once

enum class GUIElementId {
    LOAD_LEVELS = 1,
    SAVE_LEVELS = 2,
    ABOUT = 3,
    QUIT = 101,
    ADD_LEVEL = 4,
    ADD_TARGET = 5,
    ADD_LIGHT = 6,
    DELETE_SELECTED = 7,
    SAVE_LEVELS_DIALOG = 102,
    LOAD_LEVELS_DIALOG = 103,
    ABOUT_DIALOG = 104,
    MANAGER_WINDOW = 8,
    GAME_LEVEL_TREE = 9,
    LOAD_LEVEL_MESH_DIALOG = 105
};
